require: rubocop-rails
inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'db/schema.rb'
    - 'lib/tasks/*.rake'
    - 'config/environments/*.rb'
    - 'bin/**/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false